### PR TITLE
Update alpaka api

### PR DESCRIPTION
**Pull request by erikzenker**
Update alpaka calls within alpaka matmul methods.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
CI build Clang error:

```
/home/travis/build/alpaka/include/alpaka/math/acos/Traits.hpp:59:28: error: 
      'auto' return without trailing return type; deduced return types are a
      C++14 extension
        ALPAKA_FN_HOST_ACC auto acos(
                           ^
/home/travis/build/alpaka/include/alpaka/math/acos/Traits.hpp:103:43: error: 
      'auto' return without trailing return type; deduced return types are a
      C++14 extension
                ALPAKA_FN_HOST_ACC static auto acos(
                                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

maybe `BOOST_NO_CXX14_RETURN_TYPE_DEDUCTION` is not correct defined (for gcc and clang)

**Comment by BenjaminW3** [comment]
I think this is a build system error as it has not been kept in sync with alpaka since more then half a year. I will have a look at it.

**Comment by BenjaminW3** [comment]
The failing builds used boost-1.56 which is not supported by alpaka anymore.

**Comment by erikzenker** [comment]
Should we update to a newer boost version ?

**Pull request merged**
